In [25]:
from torch_linear_assignment import batch_linear_assignment

import torch 
from scipy.optimize import linear_sum_assignment
from time import time

import os


def load_data(path, limx=None, limy=None, limz=None):
    costs = torch.load(path)
    sizes = costs.size()
    if limx and limx >= sizes[0]:
        limx = sizes[0]
    if limy and limy >= sizes[1]:
        limy = sizes[1]
    if limz and limz >= sizes[2]:
        limz = sizes[2]
    return costs[:limx, :limy, :limz]

if __name__ == '__main__':
    PATH = '/root/torch-linear-assignment/data/train-end.pth'
    N_MTR = 1
    TASKS = None
    is_cuda = torch.cuda.is_available()
    print('CUDA AVAILABLE?:', is_cuda)
    # costs = load_data(PATH)
    costs = torch.IntTensor(1, 7, 5)
    if is_cuda:
        costs = costs.to('cuda')
    start = time()
    result_own = batch_linear_assignment(costs)
    end = time()
    print(f'Limit: {TASKS} {end - start} result: {result_own}')
    # result_ref = linear_sum_assignment()


CUDA AVAILABLE?: True
i=0, num_remaining=6, minVal=-1370261376.000000
i=1, num_remaining=6, minVal=32726.000000
i=2, num_remaining=6, minVal=32729.000000
i=3, num_remaining=6, minVal=32729.000000
i=4, num_remaining=6, minVal=32729.000000
Limit: None 0.00047087669372558594 result: tensor([[ 3,  2,  0,  4,  1, -1, -1]], device='cuda:0')


In [26]:
result_own.size()

torch.Size([1, 7])

In [27]:
result_own_np = result_own[0].cpu().numpy()

In [35]:
res_sp = linear_sum_assignment(costs[0].cpu().numpy())

In [29]:
padVal = costs[0, -1, -1]
for i, el in enumerate(costs[0, 0]):
    if el == padVal:
        break

In [37]:
res_sp[0], res_sp[1]

(array([0, 1, 2, 3, 4]), array([3, 2, 1, 4, 0]))

In [31]:
res_sp, result_own_np

(array([3, 2, 1, 4, 0]), array([ 3,  2,  0,  4,  1, -1, -1]))

In [40]:
costs[0][res_sp[0], res_sp[1]], costs[0]

(tensor([      32729,       32729,       32726,       32729, -1370261392],
        device='cuda:0', dtype=torch.int32),
 tensor([[  339542224,       32729,   338979184,       32729,   306746992],
         [      32729,   339558448,       32729,   339558448,       32729],
         [-1370261344,       32726,   140777392,       32729,   338505200],
         [      32729,   140777392,       32729,   140777392,       32729],
         [-1370261392,       32726,   306746992,       32729,   321067440],
         [      32729,   299354128,       32729,   339542224,       32729],
         [  321067872,       32729,   339542224,       32729,   339558448]],
        device='cuda:0', dtype=torch.int32))

In [38]:
result_own

tensor([[ 3,  2,  0,  4,  1, -1, -1]], device='cuda:0')